npm/package.json.in

- Add repository to package.json.in
- Update description
- Fix logo URL

Add repo & change naming in distribution package.json

---

CHANGELOG.md

Was mistakenly included under v0.13.0

Fix changelog for v0.14.0

---

CHANGELOG.md
api/orgs.go
cmd/machines.go
cmd/orgs.go
cmd/worklog.go
daemon/registry/machines.go
docs/qa.md

Branched from https://github.com/manifoldco/torus-cli/pull/7
Will continue to update this as code review happens for machines create.
Sample output:
```
> torus machines view -h
NAME:
torus machines view - Show the details of a machine
USAGE:
torus machines view [command options] <identity>
OPTIONS:
--org ORG, -o ORG  org to the machine will belongs to
```
```
> torus machines view 04buv5v36xecb5r390btvevkh0k10
ID:                  04buv5v36xecb5r390btvevkh0k10
Name:                api-test-machines-00cjftz6
Team(s):             machine, api-test-machines
State:               active
Created By:          jeff (Jeff Andersen)
Created On:          2016-10-30T12:56:21Z
Destroyed By:        -
Destroyed On:        -
TOKEN ID                             STATE         CREATED BY …
```

Machines view

---

CHANGELOG.md
api/machines.go
cmd/machines.go
docs/qa.md

```
> torus machines list
ID                                   NAME                              STATE         TEAM                     CREATION DATE
04buv5v36xecb5r390btvevkh0k10        api-test-machines-00cjftz6        active        api-test-machines        2016-10-30T12:56:21Z
04bh45uqk811xqzr81jb6naw5mt02        api-test-machines-b5hryd28        active        api-test-machines        2016-10-30T12:56:35Z
```
```
> torus machines destroy api-test-machines-b5hryd28
You are about to destroy a machine. This cannot be undone.
✗ Do you wish to continue? [Y/n] n
```
```
> torus machines destroy api-test-machines-b5hryd28
You are about to destroy a machine. This cannot be undone.
✔ Do you wish to continue? [Y/n] y
Machine destroyed.
```
```
> torus machines list --destroyed
ID …
```

Machines destroy command

---

api/session.go
api/users.go
apitypes/apitypes.go
base64/base64.go
cmd/debug.go
cmd/invites_send.go
cmd/login.go
cmd/middleware.go
cmd/orgs.go
cmd/status.go
cmd/teams.go
cmd/view.go
daemon/crypto/crypto.go
daemon/logic/machine.go
daemon/registry/client.go
daemon/registry/self.go
daemon/registry/tokens.go
daemon/registry/users.go
daemon/routes/routes.go
daemon/routes/session.go
daemon/session/session.go
docs/qa.md

Machines can now login using environment variables passed to the CLI via `TORUS_TOKEN_ID` and `TORUS_TOKEN_SECRET`.
Over time our support for machines will evolve to include managing the daemon as a service.

Machines login

---

daemon/daemon.go

```
Ians-MacBook-Pro-2:torus-cli ianlivingstone$ TORUS_EMAIL=test@test.com TORUS_PASSWORD=testing123456 ./torus daemon start --foreground
2016/11/01 14:12:52 v0.15.0-rc.1 of the Daemon is now listening on /Users/ianlivingstone/.torus/daemon.socket
2016/11/01 14:12:52 Attempting to login as: test@test.com
```

Support daemon login as a service

---

daemon/logic/utils.go

Just like for users, when we need to create a new keyring, ensure that
all machines that should have access to the keyring do in fact have
access.
As we do for users, for now, add *all* machines in the org, and rely on
server-side ACL blocking for access restriction.

Add machines into newly created keyrings

---

Makefile
api/machines.go
api/session.go
api/worklog.go
cmd/daemon.go
cmd/link.go
cmd/ls.go
cmd/machines.go
cmd/prefs.go
cmd/projects.go
cmd/prompts.go
daemon/logic/engine.go
daemon/logic/session.go
daemon/observer/observer.go
pathexp/pathexp_test.go
promptui/promptui.go

add `misspell` and `ineffassign` checks to our CI. Clean up all the problems too :)

Report card cleanups

---

daemon/crypto/engine.go

Replaced derrived with derived.

Fixed typo

---

Makefile
packaging/homebrew/INSTALL_RECEIPT.json.in
packaging/homebrew/torus.rb.in

Hand craft the bottles using our standard built binary, so all binary
installs use the same code. Neat!

Generate binary bottles for brew

---

cmd/profile.go

Copy pasta broke the update command

Fix command reference in profile update middleware

---

apitypes/apitypes.go
cmd/login.go
cmd/machines.go
cmd/profile.go
cmd/prompts.go
cmd/signup.go
cmd/unset.go
daemon/crypto/crypto.go
daemon/crypto/engine.go
daemon/logic/engine.go
daemon/logic/machine.go
daemon/routes/routes.go
daemon/routes/session.go

Branched from https://github.com/manifoldco/torus-cli/pull/33
Has the same dependencies.
Sample command output:
```
> torus profile update
✔ Name: Jeff Andersen
✔ Email: jeff@manifold.co
✗ Would you like to change your password?? [Y/n] n
No changes made :)
```
```
> torus profile update
✔ Name: Jeff AndersOn
✔ Email: jeff@manifold.co
✔ Would you like to change your password?? [Y/n] y
✔ Current Password: ●●●●●●●●
✔ New Password: ●●●●●●●●●
✔ Confirm New Password: ●●●●●●●●●
You are about to update your profile to the values entered above.
✔ Do you wish to continue? [Y/n] y
Name:     Jeff AndersOn
Email:    jeff@manifold.co
Username: jeff
Password: ●●●●●●●●●●
```

Change password

---

CHANGELOG.md

Missing changelog entry for the introduction of `torus profile update` and `torus profile view`

torus profile update

---

Makefile
docs/releasing.md

and check for valid aws credentials in `envcheck`.

Set aws region in makefile

---

Makefile
README.md

Everything is output in a nice format, for easy pasting around.
Closes #69

Output release artifact locations after release-all

---

CHANGELOG.md
cmd/machines.go

Give a proper message when no machines to list are found

---

docs/commands/account.md

Fix version profile was added

---

docs/concepts/path.md

Fix path links, make path example a full block

---

docs/commands/organizations.md

Add docs for worklog resolve

---

CHANGELOG.md
api/projects.go
cmd/allow.go
cmd/flags.go
cmd/ls.go
cmd/set.go
cmd/view.go
docs/commands/secrets.md
docs/concepts/path.md
pathexp/pathexp.go
pathexp/pathexp_test.go

See [command docs](https://github.com/manifoldco/torus-cli/blob/double-glob/docs/commands/secrets.md) for sample output.

Support ** in paths, change torus ls behaviour to mimic ls more closely

---

Makefile

Re-add -i for go build in Makefile

---

Makefile
api/client.go
cmd/envs.go
cmd/flags.go
cmd/orgs.go
cmd/services.go
daemon/routes/types.go
identity/identity.go
pathexp/pathexp.go
promptui/codes.go
promptui/styles.go

plus clean up the dead code it found!
The symbols in promptui will be useful when we pull it out into its own
repo, so leave them around in comments.

Add deadcode to metalinter use

---

CHANGELOG.md
promptui/select.go

Change from a manicule to a small arrow, and increase whitespace.

Update selection list pointer

---

internal/qa.md

- normalize spacing between checkbox and text
- linewrap on 80 chars
- remove no longer valid `ls` test cases

QA Doc update

---

CHANGELOG.md
Makefile

Start building our deb for ubuntu 16.10 (yakkety)

---

registry/credentialgraph.go

Unmarshaling the response when creating a new credentialgraph failed.
This was returning an error to the user, even though a new secret value
actually was set.
Fix the unmarshaling to remove the error.

Fix new credentialgraph creation

---

primitive/primitive.go
primitive/primitive_test.go

This data exists already, but was never handled in torus. Add it to
primitives, so we'll be able to use it for additional metadata about why
a secret needs to be rotated in the worklog.

Implement unmarshaling keyring membership revocation reasons

---

daemon/logic/utils.go
daemon/logic/worklog.go

When switching keyring membership correction to be user based instead of
keyring based, I neglected to consider machines. Fix this!

Re-add keyring membership correction for machines

---

registry/client.go

Change the http client to use RoundTripper in preparation for future client-side use.

Round tripper

---

cmd/prompts.go
validate/validate.go

Will be needed for upcoming client work.

Extract validation methods for common types to be reused

---

Makefile

If a `GITHUB_TOKEN` was not set, you could still release to production
but updating the GitHub release would fail.
To fix this, I've added a check to ensure a `GITHUB_TOKEN` is set before
continuing.

Ensure GITHUB_TOKEN is set before releasing

---

CHANGELOG.md
validate/validate.go

Discovered this little bug while testing out the password change bug
fix!

Name must be three characters long, not one

---

CHANGELOG.md
daemon/crypto/engine.go
daemon/logic/engine.go
daemon/logic/session.go
daemon/routes/session.go
envelope/envelope.go

When the EdDSA-based login flow was introduced support for v2 users was
forgotten.

Fix Change Password Bug

---

CHANGELOG.md
packaging/homebrew/torus.rb.in

Fix bug in Brew formula

---

CHANGELOG.md
docs/commands/secrets.md

Closes manifoldco/torus-cli#271

Clarify usage of flags when reading/writing secret

---

CHANGELOG.md
cmd/signup.go
hints/hints.go
ui/ui.go

A lot of users have forgotten their account passwords, add a reminder to
keep it secret and safe!

Remind users to keep their password safe

---

CHANGELOG.md
daemon/socket/proxy.go
registry/client.go

Closes manifoldco/torus-cli#305

Increase request deadline to 60s from 6s

---

CHANGELOG.md
cmd/orgs.go
cmd/prompts.go
cmd/utils.go
cmd/utils_test.go
docs/commands/organizations.md
primitive/primitive.go

Began 'orgs members' cmd

---

CHANGELOG.md
cmd/teams.go
docs/commands/access-control.md

Updated the output of `teams members` to match the output style of `orgs members`.

Teams list

---

CHANGELOG.md
daemon/logic/utils.go

Set key expiration to three instead of one year

---

Gopkg.lock
Gopkg.toml
api/transport_windows.go
daemon/socket/socket_windows.go

Named pipe security attributes

---

docs/start-here/quickstart.md

Add a link to an article in Manifold blog that explains in detail how TOKEN_ID and TOKEN_SECRET  should be handled. Saved my day.

Explain TOKEN_ID and TOKEN_SECRET segregation

---

ui/color.go
ui/ui.go

If stdout is not a terminal, colors should not be outputted!
Closes #343

Do not output color if stdout is not a terminal

---

CHANGELOG.md
Makefile
api/session.go
api/users.go
apitypes/apitypes.go
cmd/profile.go
cmd/signup.go
cmd/verify.go
daemon/logic/session.go
daemon/routes/routes.go
daemon/routes/session.go
docs/commands/account.md
envelope/envelope.go

When a user updates their profile they are now prompted for the
verification code.
We also display the status of their account when they run `torus profile
view`.
Closes #130

Prompt for code on email change

---

Makefile
cmd/envs.go
cmd/export.go
cmd/export_test.go
cmd/invites_list.go
cmd/list.go
cmd/machines.go
cmd/orgs.go
cmd/policies.go
cmd/profile.go
cmd/projects.go
cmd/services.go
cmd/set.go
cmd/status.go
cmd/teams.go
cmd/view.go
errs/errs.go
ui/color.go
ui/ui.go
validate/validate.go

Found error in the Makefile preventing the linters from running. Fixed error, "make ci" then caught a slew of linter errors that were previously sneaking by. The changes in this pull request address the makefile fix and the subsequent linter errors.

Fixing errors after reviving the linter checks in the makefile

---

cmd/envs.go
cmd/machines.go
cmd/orgs.go
cmd/projects.go
cmd/services.go
cmd/signup.go
cmd/teams.go
ui/color.go
ui/ui.go

A few of our list commands did not output the number of items in the
list and others did not properly colorize the integer.
I've gone through and standardized these across Torus.

Standardize list output format and coloring

---

CHANGELOG.md
api/credentials.go
cmd/envs.go
cmd/flags.go
cmd/list.go
cmd/services.go
cmd/utils.go
daemon/logic/engine.go
daemon/logic/utils.go
daemon/logic/worklog.go
daemon/routes/credentials.go
docs/commands/secrets.md
registry/credentialgraph.go
registry/envs.go
registry/services.go

Added a --team, -t flag to "list" command. This let's users filter base don what secrets a certain team or group of teams have access to. Leverages new ACL changes in the server.

Team filter
