cmd/flags.go, cmd/prompts.go, cmd/set.go, cmd/unset.go, prefs/prefs.go, promptui/prompt.go, promptui/promptui.go
This prevents users from accidentally destroying something unintended.
Right now our only destructive command is `unset`
```
> torus unset testunset
You are about to unset "/jeff/all-projects/dev-jeff/default/*/*". This cannot be undone.
✗ Do you wish to continue? [Y/n] n
> torus unset testunset
You are about to unset "/jeff/all-projects/dev-jeff/default/*/*". This cannot be undone.
✔ Do you wish to continue? [Y/n] Y
Credentials retrieved
Keypairs retrieved
Encrypting key retrieved
Credential encrypted
Completed Operation
Credential testunset has been unset at /jeff/all-projects/dev-jeff/default/*/*/testunset.
```
```
> torus set testunset 1234 -y
Credentials retrieved
Keypairs retrieved
Encrypting key retrieved
Credential encrypted
Completed Operation
Credential testunset has been set at …
```
=> Add confirm dialogue for destructive commands

api/client.go, api/machines.go, api/teams.go, apitypes/claimtree.go, apitypes/machines.go, base64/base64.go, cmd/flags.go, cmd/machines.go, cmd/prompts.go, cmd/teams.go, daemon/crypto/crypto.go, daemon/crypto/engine.go, daemon/logic/engine.go, daemon/logic/machine.go, daemon/logic/utils.go, daemon/logic/worklog.go, daemon/registry/claimtree.go, daemon/registry/client.go, daemon/registry/machines.go, daemon/registry/users.go, daemon/routes/machines.go, daemon/routes/routes.go, daemon/routes/session.go, daemon/routes/types.go, daemon/session/session.go, docs/qa.md, identity/identity.go, primitive/primitive.go, promptui/select.go
Introducing the ability to create a machine!
**UI**
``` bash
Ians-MacBook-Pro-2:torus-cli ianlivingstone$ ./torus machines create --help
NAME:
torus machines create - Create a machine for an organization
USAGE:
torus machines create [command options]
OPTIONS:
--org ORG, -o ORG     the org the machine will belong too
--team TEAM, -t TEAM  the team the machine will belong too
Ians-MacBook-Pro-2:torus-cli ianlivingstone$ ./torus machines create
✔ Org name: test
✔ Select Machine Team: api
✔ Enter machine name: api-98g4vw63
Creating machine "api-98g4vw63"
Generating machine token
Generating token keypairs
Uploading token keypairs
Creating keyring memberships for token
Uploading keyring memberships
Machine created
You will only be shown the secret once, please keep it safe.
Machine ID: …
```
=> Machines Create

CHANGELOG.md, api/machines.go, cmd/flags.go, cmd/machines.go, docs/qa.md
Branched from https://github.com/manifoldco/torus-cli/pull/6
Will continue to update this as code review happens for machines create.
Sample output:
```
> torus machines list --help
NAME:
torus machines list - List machines for an organization
USAGE:
torus machines list [command options]
OPTIONS:
--org ORG, -o ORG     Org to the machine belongs to
--team TEAM, -t TEAM  Team the machine belongs to
--destroyed, -d       Display only destroyed
```
```
> torus machines list
ID                                   NAME                              STATE         TEAM                     CREATION DATE
04buv5v36xecb5r390btvevkh0k10        api-test-machines-00cjftz6        active        api-test-machines        2016-10-30T12:56:21Z
04bh45uqk811xqzr81jb6naw5mt02        api-test-machines-b5hryd28 …
```
=> Machines list

daemon/session/session.go
A change introduced in machine login prevented a user from logging in
without logging out again.
I've re-introduced this behaviour.
=> Support logging in without logging out

cmd/machines.go
It was showing the error from the failed machine ID parse (when a name is supplied), rather than showing the "machine not supported" error returned from the lookup.
```
> torus machines view api-g98fnb9z
Failed to retrieve machine.
Unauthorized: Feature not supported by Machines
```
=> Display correct error when lookup fails by name during machines view

cmd/daemon.go, cmd/run.go
Now that we've introduced `TORUS_TOKEN_ID` and `TORUS_TOKEN_SECRET` we
need to ensure we don't pass these on to downstream processes.
At the same time, I've consolidated the filtering logic!
=> Filter sensitive env vars on run and daemon start

cmd/view.go
In order to differentiate between a user and machine's identity in the
path we preprend a `machine-` (as users are global and could have the
same name as a machine which is org scoped).
=> A machines identity is  prepended with 'machine-'

daemon/daemon.go, daemon/logic/engine.go, daemon/logic/session.go, daemon/routes/routes.go, daemon/routes/session.go, daemon/socket/proxy.go
In preparation for supporting machine and user login by running the
daemon as a service, I've moved the login/logout flow into the logic
engine.
The daemon will then construct the logic engine at startup and pass it
into the router for future use.
=> Move Login and Logout flow into LogicEngine

api/client.go, apitypes/apitypes.go, cmd/allow.go, cmd/login.go, cmd/logout.go, cmd/orgs.go, cmd/policies.go, cmd/projects.go, cmd/services.go, cmd/teams.go, cmd/worklog.go
Related to https://github.com/manifoldco/torus-cli/issues/25
We've had a number of users in unverified states end up confused about why commands are failing because we weren't surfacing enough context. This adds more context to Unauthorized error situations, and updates a lot of cases where we were eating the error in favour of a generic.
```
> torus link
✔ Select organization: unverifieduser
Project selection failed.
Unauthorized: Your account has not yet been verified.
Please check your email for your verification code and follow the enclosed instructions.
Once you have verified your account you may retry this operation.
```
=> Prevent hiding of errors, add context to Unauthorized errors

cmd/orgs.go
Summary of problem: Wrong message displayed when removing a user from an org fails.
What happened:
```
> torus orgs remove peterkaminski
Could remove user from the org. Please try again.
```
What I expected:
```
> torus orgs remove peterkaminski
Could not remove user from the org. Please try again.
```
Summary of fix: Added "not " to error message.
Since the change is trivial and I don't have a dev environment set up, I did not run through the QA checklist.  I hope the project maintainer can test, or, it's okay to bounce this PR, and get bug fixed another way.
I did not add `meta/in-progress` and `component/cli` labels because they were not available in the "Labels" dropdown in github.
=> typo fix for orgsRemoveFailed

cmd/signup.go
We should surface this context until we can update the server to provide more granularity.
=> Extend email in use error to include username

CHANGELOG.md, cmd/flags.go, cmd/ls.go, cmd/run.go, cmd/set.go, cmd/view.go
Introduce flags for specifying user or machine identities through
commands that manipulate secrets (set, unset, run, view, etc).
The machine flag automatically prepends `machine-`, ensuring users don't
have to worry about the complexities of the credential path.
Stringing together multiple `--user` and `--machine` flags will turn
them into an OR expression (e.g. `[ian|machine-api-staging-1231fd]`).
=> Support --user and --machine flags for set, etc.

CHANGELOG.md, cmd/allow.go, cmd/deny.go, cmd/flags.go, cmd/machines.go, cmd/policies.go, cmd/prompts.go, cmd/teams.go, docs/qa.md, primitive/primitive.go
This pull request introduces the concept of "machine roles" to the CLI which are powered using the "team" primitive.
The fundamental difference between a user and a machine is that a machine can only belong to *one* team other than the main `machines` system team which is the team that defines the role of the machine.
Included in this request:
- Bug fix to prevent a panic occurring when listing teams with an unknown org
- Remove capability to list machines through `torus teams list` or `torus teams members`
- Introduce the `torus machines roles` and `torus machines create-role` commands for listing and creating machine roles.
**UI**
```
Ians-MacBook-Pro-2:torus-cli ianlivingstone$ ./torus machines roles
machine             [system]
hellomachines
joe
axe
fdf
All machines belong to the …
```
=> Expose Machine Teams as Roles

Makefile, packaging/homebrew/torus.rb.in
We can't pick a specific go version for the brew build, so bypass the
check.
For staging prerelease builds, put the formula under a version dir, so
the name matches the class contained within.
=> Teach brew install to bypass go check

docs/qa.md
We don't support listing machines through `torus teams list` or `torus
teams members` anymore!
=> Update machines qa checklist

docs/qa.md
We don't have one anymore!
This also removes QA steps for the website, but that's on a different
cadence, and can handle its own QA.
=> Remove waitlist from QA template

CHANGELOG.md, cmd/flags.go, cmd/status.go, cmd/view.go
The status command's "credential path" was not displaying properly for
machines (it was not prepending "machine-").
=> Status command not display identity properly

Makefile, packaging/deb/Dockerfile, packaging/deb/control.in, packaging/deb/distributions.debian, packaging/deb/distributions.ubuntu
The package is all the same, but releases are broken out for the most
recent debian release, and the last two ubuntu releases. This lets us
craft an apt sources.list line that is familiar to users (including the
distro code name), and provides a nice cut-point for supporting upstart
vs systemd, if we can't fit them both into a single deb.
=> Add deb/apt releases

Makefile, cmd/flags.go, glide.lock, glide.yaml, tools/cdn-indexer/index.html.tmpl, tools/cdn-indexer/main.go
tools/cdn-indexer reads the existing files from s3 and generates a
templated index file, then writes it back to s3. It is run during the
`release-all` Makefile target.
This is on top of #50. I'll rebase after that's merged.
=> Generate static directory listings for get.torus.sh

api/users.go, apitypes/apitypes.go, cmd/profile.go, cmd/prompts.go, cmd/signup.go, cmd/status.go, daemon/registry/users.go, daemon/routes/routes.go, daemon/routes/session.go, daemon/session/session.go
- `torus profile update`
- Depends on a new route in the registry
- Allows user to update name or email address
- Email will require re-verification on change
=> Allow user to update their name or email

CHANGELOG.md, apitypes/credential.go, cmd/view.go
Implement `--format` supporting `env, json, and verbose` for displaying
secrets with the default being (env).
```
$ torus help view
NAME:
torus view - View secrets for the current service and environment
USAGE:
torus view [command options]
CATEGORY:
SECRETS
OPTIONS:
--org ORG, -o ORG                 Use this organization.
--project PROJECT, -p PROJECT     Use this project.
--environment ENV, -e ENV         Use this environment.
--service SERVICE, -s SERVICE     Use this service. (default: default)
--user USER, -u USER              Use this user.
--machine MACHINE, -m MACHINE     Use this machine.
--instance INSTANCE, -i INSTANCE  Use this instance. (default: 1)
--format FORMAT, -f FORMAT        Format used to display data (json, env, verbose) (default: env)
--verbose, -v …
```
=> Add --format option to view (json, env, verbose)

config/config.go
Leave it up to the daemon to create the daemon dir, everything in it,
and ensure the perms are correct.
CLI commands are only responsible for knowing where this directory is,
so they can access the socket/pid.
This will simplify the system-wide machine token use case.
=> The daemon should be in control of its directory

cmd/daemon.go, config/config.go
For the system wide daemon machine case, we want to have looser
permissions on the torus root dir.
Introduce a hidden flag to bypass permission checks on the torus root
dir, so we can allow the system install to take care of permissions
instead.
=> Allow bypassing torus root permission checks

CHANGELOG.md, cmd/daemon.go, contrib/systemd/token.environment, contrib/systemd/torus.service, daemon/daemon.go, daemon/socket/proxy.go, packaging/rpm/torus.spec
The service can be configured with machine token credentials in
/etc/torus/token.environment, for use in production environments.
Other processes running on the system can access secrets from torus by:
- running as a user in the `torus` group
- setting the TORUS_ROOT environment variable to /var/run/torus
While there is a torus user, this user should *not* be used for running
processes that need access to secrets. It is an isolated sandbox that
has access to the machine's token credentials.
=> Include a systemd service with our rpm

Makefile, api/invites.go, api/memberships.go, api/policies.go, api/session.go, api/users.go, cmd/login.go
Use it via gometalinter now, so imports are all correct.
Fix the identified issues, and use a temporary fork of go-bindata so it
won't generate un-simple files.
=> Fix build times with gosimple

cmd/status.go
The identity is included in the path, so it should be displayed in the breakout.
=> Introduce identity to status breakout

Makefile
Then we don't have to worry about identifying which files to run against.
I've also switched to using the `-s --skip` flag to skip over the `data` dir, so we don't have to care about go-bindata's output, removing the need for a fork.
=> Run all linters with gometalinter

Makefile
Files with unique names per release have a one week cache expiry.
Files with reused names (ie yum repomd.xml) have a 5 minute cache
expiry.
Closes #55
Further, generate a proto manifest.json for the CDN. This file contains the latest version number, and when it was released, for use on the www.torus.sh site.
=> Cdn content type and good caching

CHANGELOG.md, cmd/profile.go, daemon/routes/session.go
Closes https://github.com/manifoldco/torus-cli/issues/71
When updating both email and password a user would receive an "unauthorized" message.
This was because the login attempt was using the _old_ email address.
This fix ensures the request uses the most up to date information.
=> Fix unauthorized error during profile update

CHANGELOG.md, cmd/allow.go, cmd/deny.go, cmd/envs.go, cmd/link.go, cmd/login.go, cmd/logout.go, cmd/machines.go, cmd/policies.go, cmd/prefs.go, cmd/projects.go, cmd/services.go, cmd/signup.go, cmd/status.go, cmd/teams.go, cmd/unlink.go, cmd/verify.go
```
NAME:
torus - A secure, shared workspace for secrets
USAGE:
torus [global options] command [command options] [arguments...]
VERSION:
0.17.0
COMMANDS:
help, h  Shows a list of commands or help for one command
ACCESS CONTROL:
allow     Increase access given to a team or role by creating and attaching a new policy
deny      Decrease access given to a team or role by creating and attaching a new policy
policies  Manage which resources machines and users can access
teams     Manage teams and their members
ACCOUNT:
login    Log in to a user account, authenticating the CLI
logout   Destroy the current active session, unauthenticating the CLI
profile  Manage your Torus account
signup   Create a new Torus account
verify   Verify an email address for your account
ORGANIZATIONS:
invites   View …
```
=> Re-organization of commands, in preparation for docs

CHANGELOG.md, Makefile, packaging/deb/postinst
All of the deb based distros we support use systemd, so we don't need an
upstart configuration.
Closes #74
=> Add systemd machine setup for deb packaging, too!

Makefile, cmd/machines.go, tools/cmdlint/main.go
For starters it enforces ordering of standard subcommand names.
=> Create cmdlint for linting our commands

CHANGELOG.md, apitypes/worklog.go, cmd/worklog.go, daemon/logic/utils.go, daemon/logic/worklog.go, daemon/routes/worklog.go
```
$ ./torus worklog list --org badkeys
IDENTITY         TYPE      SUBJECT
0a74q6462ymxf5g  keypairs  badkeys
$ ./torus worklog resolve --org badkeys
✔  0a74q6462ymxf5g  Keypairs generated.
$ ./torus worklog list --org badkeys
IDENTITY  TYPE  SUBJECT
```
=> Support creating missing keypairs via worklog

CHANGELOG.md, apitypes/worklog.go, cmd/profile.go, cmd/prompts.go, cmd/worklog.go, daemon/logic/worklog.go, daemon/registry/org_invite.go
Invite approval (the last step to add a user to an org after they've
accepted their invite) can be resolved automatically, but should still
prompt the user for confirmation, in case they've changed their mind
about giving someone access.
Support invite approval in the worklog, with a confirmation prompt.
=> Add invite approval to the worklog

cmd/profile.go, promptui/prompt.go
And lowercase the y/n prompt, as the default in all cases is really
`no`.
=> Remove duplicate ? for change password

CHANGELOG.md, cmd/cmd.go, cmd/debug.go, cmd/link.go, cmd/middleware.go, cmd/prefs.go, cmd/prompts.go, cmd/status.go, config/config.go, main.go, prefs/prefs.go, ui/ui.go
- Introduces `ui` package, which will be home to any ui output functions
- Will come in handy as we standardize all outputs per the style guide
- Adds prefs for `core.hints` and `core.progress` to enable (default) or disable these outputs
=> Add prefs for core.hints and core.progress

daemon/logic/credential_graph_set.go, daemon/logic/credential_graph_set_test.go, daemon/logic/engine.go, prefs/prefs.go
credentialGraphSet.Prune returns all CredentialGraphs within the
credentialGraphSet that are still active (they have reachable
credentials). Further, it only returns the credentials in each graph
that are still active.
Use Prune for view operations, so we can be sure that even before we
decrypt credentials, we are only returning the active version of a
credential.
Closes #98
=> Introduce daemon side credential pruning

CHANGELOG.md, cmd/debug.go, cmd/version.go
If we can't reach the server, still display the client and daemon
version info, and include error details for the unknown value.
Closes #1218
=> Display as much info as possible in `version`

CHANGELOG.md, config/config.go
With the credentialgraphset.prune changes, we can now bump our api
version to 0.2.0 and fetch the *full* credential graph.
=> Bump the requested api version

docs/commands/organizations.md, docs/commands/secrets.md, docs/commands/system.md
This makes the options look better in markdown, but we'll hide the headings for command options in the actual docs html/css.
=> Add headings to command option tables

Makefile
Including the real GOROOT and GOPATH in the released binary isn't
useful. Strip them out.
=> Remove local file paths from released binary

CHANGELOG.md, cmd/allow.go, pathexp/pathexp.go
Closes https://github.com/manifoldco/torus-cli/issues/131
- Ensure secret name is supplied and is valid
- Catch invalid org name before roundtrip to server
=> Perform additional validation for partial paths in access

cmd/allow.go
If we see a doubleglob at the end of a path, treat it as a fullglob
secret.
Closes #131
=> Permit ending doubleglob in allow/deny

CHANGELOG.md, cmd/ls.go
When you have two credentials with the same name, but different paths, they would not show up in the output of `torus ls`. This is expected during `view` due to specificity checks and context, but with `torus ls` you want to see all of the values.
=> Do not filter by specificity during torus ls

Makefile, daemon/observer/observer.go, daemon/observer/observer_test.go
The tests described in the test file didn't really describe a real world
situation. In the real world, an observer is either always present and
started well before we send notifications or no observer will be ever
present at all.
Running the tests, a deadlock occurred sometimes, locking up the tests
and eventually failing them. This was because the Observer in our tests
didn't register itself in time before we created a new notification. The
notification then got sent through the system and dropped because no
observer was present. Once the observer then started, it would keep listening
until the notification came through, resulting in a deadlock since the
event was already dropped beforehand.
This patch does actually not fix the deadlock situation itself, it is
still possible to happen - …
=> ObserverTest: prevent a deadlock situation.

apitypes/worklog.go, daemon/logic/engine.go, daemon/logic/worklog.go, daemon/routes/worklog.go
Extract out the `List` and `Resolve` logic for each worklog item type
into new structs that implement a common `handler` interface.
This keeps the logic for each type distinct, which should (hopefully)
make for easier reading, and easier addition of new item types.
With the logic now distinct and behind a map lookup, take advantage of
this during `Get` and `Resolve` to extract the item type from the
requested ID, and only lookup that type of item, bypassing all the
others.
=> Put worklog item type logic into their own types

api/client.go
Calling close is none blocking, it closes the channel immediately and
reads will still happen from the `stream.Events` channel instead of the
`<- done` channel.
We want to block here until the message is actually read from the done
channel so we can continue processing the end result and not show other
event messages.
There is also an extra goroutine spun up when there's an error 
unmarshaling the event:
When an error happens in unmarshaling the JSON, we'll end up in a
deadlock. This is because we do a return, ending the for and select
loop, which listens on the done channel. This means that nothing will
ever get read from the done channel. On line 166, we try to put
something on the done channel and block until it's read.
This goroutine acts as a reader for that channel and will unblock …
=> APIClient: drop event messages after action is processed.

CHANGELOG.md, cmd/invites_list.go, cmd/invites_send.go, cmd/link.go, cmd/ls.go, cmd/machines.go, cmd/orgs.go, cmd/prefs.go, cmd/profile.go, cmd/prompts.go, cmd/set.go, cmd/signup.go, cmd/teams.go, cmd/unset.go, cmd/view.go, hints/hints.go, main.go, promptui/prompt.go, ui/ui.go
Closes https://github.com/manifoldco/torus-cli/issues/96 https://github.com/manifoldco/torus-cli/issues/139
We want to help users discover the next steps they may want to take after executing a command. Previously we added a pref `core.hints` to enable whether these will be displayed, these hints are behind this flag.
`hints.Display` takes a list of hint categories (which are lists of strings). It chooses a random category to display a hint for, then chooses a random hint from that list.
=> Add ui.hints throughout core commands

CHANGELOG.md, apitypes/worklog.go, daemon/logic/utils.go, daemon/logic/worklog.go, daemon/registry/keyring.go
If an invite or machine creation fails partway through, we can end up in
a state where the user/machine is created, but are not given access to
all keyrings, and the secrets therein.
Teach the worklog how to identify and resolve this problem.
=> Teach the worklog how to correct keyring memberships

docs/commands/system.md, hints/hints.go
Now that the tips have been implemented, disabling them should be documented.
=> Missing doc for core.hints

CHANGELOG.md, api/keypairs.go
Deserializing the claims structure for a keypair was not correct, which
would cause panics. Fix this.
=> Ensure keypairs generate does not panic with existing keypairs

CHANGELOG.md, api/keypairs.go, apitypes/claimtree.go, cmd/keypairs.go, daemon/logic/engine.go, daemon/logic/utils.go, daemon/logic/worklog.go, daemon/registry/claims.go, daemon/registry/client.go, daemon/routes/keypairs.go, daemon/routes/routes.go, daemon/routes/types.go
This command is purely for testing and debugging; real revocation will
come packaged in a nicer form, bundled with other actions.
Along with this, teach `keypairs list` to display the actual validity
state of a keypair.
related: #153
=> Introduce the hidden keypairs revoke command

CHANGELOG.md, daemon/logic/utils.go, daemon/registry/keyring.go, internal/qa.md
Only return unrevoked keyring memberships
When looking for a keyring membership, skip over any memberships that
match the user/machine token, but have been revoked; only return active
unrevoked memberships.
With this, the worklog can detect when a user was once in a keyring, had
their membership revoked, and then need to be re-added.
=> Worklog keyring regenerated keys

CHANGELOG.md, cmd/set.go
We support types for credentials, which is nice. However, we can't
accurately know if a string given to us on the command line that *looks*
like a number really should be a number.
If we assume it should be a number, we end up losing data, like leading
zeros, or converting long decimals to scientific notation.
For values given on the command line, stop attempting to convert the
value, and instead store it as a string.
Closes #163
=> Stop attempting to convert credentials to numbers

main.go
To catch all cli templates that use the name in output. You can never
have too many names!
Closes #167
=> Set HelpName as well as Name

CHANGELOG.md, Makefile, glide.lock, glide.yaml, internal/releasing.md, tools/gh-releaser/main.go
Tie our tags to proper github releases. Include the relevant changelog
entry if it exists. Mark -rc releases as prerelease.
=> Create github releases when releasing

daemon/routes/session.go, registry/users.go
The server now supports an optional state field being supplied during
signup, so we can remove the duplication inside the CLI code base!
=> Remove Signup Object

api/client.go, cmd/invites_list.go, cmd/teams.go, registry/claims.go, registry/claimtree.go, registry/client.go, registry/credentialgraph.go, registry/credentials.go, registry/envs.go, registry/keypairs.go, registry/keyring.go, registry/keyring_member.go, registry/machines.go, registry/memberships.go, registry/org_invites.go, registry/orgs.go, registry/policies.go, registry/profiles.go, registry/projects.go, registry/round_tripper.go, registry/self.go, registry/services.go, registry/teams.go, registry/tokens.go, registry/users.go, registry/utils.go, registry/version.go
RoundTrip is a convenience function that combines request creation with
execution. Putting these two calls together reduces the error checking
each call pair had to do before by one. This adds up, over all the
calls!
=> Registry roundtrip convenience call

cmd/envs.go, cmd/projects.go, cmd/services.go, registry/envs.go, registry/projects.go, registry/services.go
A nil slice is effectively the same as a zero length slice. Use nil
slices instead of a nil pointer to a slice for empty arguments to
registry calls, making things simpler.
Built on top of #179
=> Fewer registry pointers

api/client.go, api/credentials.go, api/keypairs.go, api/machines.go, api/org_invites.go, api/session.go, api/users.go, api/version.go, api/worklog.go
Like RoundTrip for registry, DaemonRoundTrip is a convenience function
that combines request creation with execution. It includes optional
progress output.
=> Daemon round trip

CHANGELOG.md, api/session.go, api/users.go, cmd/profile.go, cmd/signup.go, config/config.go, daemon/crypto/crypto.go, daemon/logic/machine.go, daemon/logic/session.go, daemon/routes/session.go, daemon/session/session.go, envelope/envelope.go, primitive/primitive.go, registry/self.go, registry/tokens.go, registry/users.go
The version 2 user schema uses passphrase derived public key
authentication for creating auth tokens.
New signups will be created as v2 Users, while v1 Users will be upgraded
to v2 during the authentication process.
Once a user has upgraded to v2, the old (now deprecated) hmac based
authentication flow will no longer be allowed.
Cliff notes of changes made:
* Introduction of UserInf interface (common access layer for v1 and v2 Users)
* Convenience method for accessing the underlying `byte` array for the
base64 package.
* Bump to supporting Registry API version `0.3.0`
* Introduction of the `Token` primitive type and envelope
=> Introduce v2 User w/ Upgrade from v1->v2

CHANGELOG.md, daemon/logic/worklog.go
If a user is missing access to a keyring, but they don't have a valid,
unrevoked keypair, don't generate worklog items for other users to add
them to the keyring; they won't be able to until the user has a valid
keypair.
=> Don't create keyring worklog entries for keypairless users

CHANGELOG.md, cmd/link.go, config/config.go, docs/commands/project-structure.md
We no longer create a default service during link, instead we rely upon
the registry to create it for us.
=> Remove 'default' service creation from link cmd

daemon/session/session.go
When creating a machine, we build a temporary session to generate the
machine's login details.
Machines do not require the token portion of the session to be set;
rather than putting in a dummy value, check for the type.
=> Fix machine creation

CHANGELOG.md, daemon/logic/worklog.go
`keyring` type worklog items are now organized by user, not keyring. Keyrings
are internal structures that hold secrets; they shouild rarely appear in the
UI. Focusing on users that are missing access they should have is much more
understandable.
=> organize worklog keyring items by user, not keyring

.gitignore, Dockerfile, Makefile
A recent change to glide broke our CI process. Let's try and eliminate
that, and use released versions only!
=> Install released versions of glide only

api/worklog.go, apitypes/worklog.go, cmd/worklog.go, daemon/logic/credential_graph_set.go, daemon/logic/credential_graph_set_test.go, daemon/logic/worklog.go, registry/keyring.go
Populate rich worklog details
For each worklog item type, attach a Details struct containing type
specifid information (such as teams pending for an invite, etc).
Use some of this data for generating the item subject and summary string
in the cli, rather than the daemon.
This data will be used for presenting extra data in the worklog, and
formatting it in a most joyful manner.
=> Worklog details structure

CHANGELOG.md, api/worklog.go, apitypes/worklog.go, cmd/profile.go, cmd/prompts.go, cmd/worklog.go, daemon/logic/worklog.go, daemon/routes/worklog.go, promptui/codes.go, promptui/codes_test.go, promptui/prompt.go, promptui/promptui.go, promptui/select.go, promptui/styles.go
Final changes needed for our new worklog ui (except line wrapping ;) )
The bulk of this is just the rewrite of `cmd/worklog.go`, but there are a few secondary bits too:
- minor changes to `ui` and `promptui`
- split out user vs machine keyring rotation types
- remove the worklog result type (using details and error results instead).
=> The great worklog ui revamp

daemon/daemon.go, daemon/logic/engine.go
For the browser client we need to remove the dependency on config so that prefs is not included (gopher js does not support any system related calls).
Also adds a database interface to remove the boltdb dependency which is not used.
=> Remove config dependency from logic engine

base32/base32.go, base32/base32_test.go
We should add no padding, not full padding.
=> Fix padding addition for base32 when divisible by 8

api/client.go, api/transport.go, api/transport_windows.go, registry/client.go
This implements a patch to address issue #210.
I've set up a 1 second timeout for the Dial and a 30s timeout for actual requests.
@jbowes @ianlivingstone do you think 30s is good enough for actual requests or should we consider something else?
**Note:** this depends on #207 to be merged in. [This](https://github.com/jelmersnoeck/torus-cli/compare/jelmer/123-windows-support...jelmersnoeck:jelmer/210-transport-timeout?expand=1) is the actual diff whilst that one isn't merged in yet.
closes #210
=> Transport timeouts.

CHANGELOG.md, cmd/flags.go
A naive "strings.Contains" was used instead of "HasPrefix" for checking
whether or not a machine identity was valid.
Closes manifoldco/torus-cli#222
=> Fix machine name check

cmd/set.go, cmd/set_test.go
Hey, my first instinct while use `torus set` is to use the export variable syntax `KEY=value` instead of `KEY value`. This PR allows that when only one argument is passed.
Some scenarios are described in the test cases. Let me know if there is something else that needs to be covered.
Closes https://github.com/manifoldco/torus-cli/issues/219
=> Support `torus set KEY=value` syntax

cmd/invites_list.go, cmd/invites_send.go, cmd/link.go, cmd/ls.go, cmd/machines.go, cmd/orgs.go, cmd/set.go, cmd/teams.go, cmd/view.go, hints/hints.go, hints/hints_test.go, main.go
* Create constant list of command hints to avoid misspellings or commands
not defined;
* Change `Display` to accept a variadic list of command hints;
* Rename `Init()` to `init()` since no custom package initialization was
required;
* Create `randHint` function to avoid testing IO from readline.
PS: `Set` doesn't have hints defined yet.
=> Change `hints.Display` to receive constant list

CHANGELOG.md, cmd/set.go, cmd/set_test.go, docs/commands/secrets.md
With the acceptance of #234, we needed to update the changelog, `torus
set` documentation and clarify a few of the new error messages.
=> Update Changelog, Error Messages, and Docs

CHANGELOG.md, cmd/debug.go, cmd/prompts.go, docs/commands/account.md
Throughout, we were referencing both a "Name" and a "Username", with
this change we now differentiate by asking for a "Full Name" and a
"Username".
Closes #233
=> Rename "Name" to "Full Name"

cmd/allow.go, cmd/policies.go, pathexp/pathexp.go, pathexp/pathexp_test.go
This MR is a first attempt at the `torus policies test` command as specified in Ian's email.
Testing a path to see if all relevant policy allows access to it goes something like this:
- validate input
- fetch org
- fetch user teams
- fetch user profile
- fetch all teams for org
- fetch memberships for each team and filter team by user membership
- fetch all policies for org
- fetch all policy attachments for org
- filter policies
- by team attachment
- by path
- by action
- test access (yes if >= 1 policies allow access and 0 deny access, false otherwise).
Notes:
- I've followed the existing pattern in policies.go and elsewhere in other command implementations that making API calls can be  expensive and should be done in parallel when possible.
- When implementing the above pattern, I …
=> policies test cmd initial implementation

cmd/view.go, cmd/view_test.go
Closes #265
I changed the printXXXFormat APIs to accept an `io.Writer` instead of always using `os.Stdout`. Makes easier to test and we can combine with another writers if needed.
I also removed the hint from the view command because the text is added to the output file when redirecting. 
Eg: `torus view > secret.env` has at the end:
```
[1mProtip: [0mDefine an organization and project for your current working directory using `torus link`
```
Probably a better approach would be to disable hints whenever stdout is not printing to the terminal.
=> Wrap secret value with multiple words in quotes using view command

cmd/import.go, cmd/import_test.go, cmd/set.go, cmd/set_test.go, cmd/view_test.go, glide.lock, glide.yaml, hints/hints.go
If no arguments are passed to `set` we try to check if there is any input being piped to stdin. Closes #218 
Given a `file.txt` like:
```
user=root
password=s3cr3t
port=3000
```
We can now do:
```shell
torus set --org example --project mvp < file.txt
```
It is also useful to export all secrets from one organisation / project and add to another one:
```
torus view --org example --project foo > secrets.txt
torus set  --org another --project bar < secrets.txt
```
@ianlivingstone I'm currently doing a round trip to set each secret. I'm not sure if there is a way to send multiple secrets in a single payload.
=> Allow set cmd to read from a file piped to stdin

.travis.yml
On June 21st Travis CI updated their Ubuntu Trusty installations (https://blog.travis-ci.com/2017-06-19-trusty-updates-2017-Q2 and https://blog.travis-ci.com/2017-06-21-trusty-updates-2017-Q2-launch), which seems to have changed the `docker-engine` package to be `docker-ce` based on Docker's updated naming scheme.
This PR changes to apt-get to install `docker-ce` instead of `docker-engine`
=> Use docker-ce instead of docker-engine for Docker on Ubuntu

cmd/gatekeeper.go, cmd/machines.go, gatekeeper/bootstrap/aws/bootstrap.go, gatekeeper/bootstrap/bootstrap.go, gatekeeper/client/client.go, gatekeeper/gatekeeper.go, gatekeeper/http/http.go
This pull request starts to add optional SSL for the Gatekeeper bootstrap tool. This would start progress on #248.
This adds --cert, --key (`TORUS_GATEKEEPER_CERT` and `TORUS_GATEKEEPER_CERT_KEY`) to the `torus gatekeeper start` command, and `--ca` (`TORUS_BOOTSTRAP_CA`) to the `torus machines bootstrap` to start the service with TLS.
Some considerations: the certificate would need to be signed by a CA in the bootstrapping system's CA bundle. There may be cases where a user would use a self-signed cert, or a cert signed by an internal CA. In that case, the certificates would need to be added to the system's certificate bundle, or else the bootstrapping will fail on a bad certificate. The `--ca` flag will override using the system's certificate bundle.
It might be something to explore to …
=> Add optional SSL for Gatekeeper

CHANGELOG.md, config/config.go, daemon/daemon.go, daemon/socket/proxy.go, daemon/updates/updates.go, daemon/updates/updates_test.go, daemon/utils/utils.go, prefs/prefs.go, primitive/zz_generated_primitive.go, tools/primitive-boilerplate/main.go
This pull request contains several changes to fix various bigs inside the version checking code.
- The daemon will no longer crash if it cannot talk to `get.torus.sh` for any reason
- The daemon will check for the latest version at start up *and* its regular interval
- The daemon now leverages the CABundle for retrieving the manifest from `get.torus.sh`
Closes manifoldco/torus-cli#261
=> Fix bugs in version checking

CHANGELOG.md, README.md, packaging/npm/package.json.in
Now that we have a win32 alpha client, let's advertise it's support on
win32 via npm! Conventiantly, this also gives us an installation
mechanism for the windows alpha!
=> Advertise torus installation via npm on win32

CHANGELOG.md, api/credentials.go, cmd/import.go, cmd/set.go, cmd/unset.go, daemon/logic/engine.go, daemon/routes/credentials.go, docs/commands/secrets.md, internal/qa.md, registry/credentials.go
To speed up `torus import`, we now send multiple credentials to the
server in a single request.
=> Add import documentation and support multi-credential creation

Makefile
gometalinter recently switched from using go's built in `go vet` tool to
a fork to fix several bugs that their users have experienced. However as
a result this broke the Torus build as we were not using `gometalinter
--install` to bring in the various linters.
To fix this in the short term, I've switched our bootstrap setup to use
`gometalinter --install` and opened an issue for properly vendoring our
bootstrap dependencies (#286).
Ref Discussion: https://github.com/alecthomas/gometalinter/pull/375
=> Use gometalinter --install to acquire linters

CHANGELOG.md, Makefile, packaging/npm/package.json.in, packaging/npm/passthrough.js
If a user installs `torus` but fails to install `kexec` then
`passthrough.js` will fallback to spawning torus in a child process
instead of having it inherit the current process.
Conditional installation of `kexec` is handled by the
`optionalDependencies` section of the `package.json`.
Closes #284
=> Fallback to spawn if kexec not available via npm

CHANGELOG.md, cmd/policies.go, docs/commands/access-control.md, docs/commands/organizations.md, docs/concepts/policies.md, internal/qa.md
This commit introduces the new `torus policies attach` command allowing
users to attach a policy to multiple teams and machine roles within an
organization.
Included is a small update to the documentation to clarify that a `role`
is a `machine-role`.
=> Introduce 'torus policies attach'

CHANGELOG.md, cmd/allow.go, cmd/deny.go, cmd/flags.go, docs/commands/access-control.md, internal/qa.md, validate/validate.go
When generating a policy using `allow` and `deny` you can now specify a
name and description as optional command line flags.
=> Introduce ability to name and describe a policy

CHANGELOG.md, cmd/policies.go, docs/commands/access-control.md, registry/policies.go
Using `torus policies delete` a user can now delete a policy and all of
it's attachments inside an organization.
**Example**
```bash
$ torus policies delete --yes read-production
Policy read-production and all of it's attachments have been deleted.
```
=> Introduce the ability to delete a policy

CHANGELOG.md, cmd/signup.go, hints/hints.go, prefs/prefs.go
No longer ask to enable hints, do it by default and remind the user
about `torus link` at the end of the signup flow!
Finally, actually enable check updates :)
=> Dont ask to enable hints, add link protip to signup

CHANGELOG.md, cmd/import.go
A bug was introduced to the import command where it'd set secrets using
the value instead of the name.
Closes manifoldco/torus-cli#296
=> Use the proper name when importing from a file

cmd/import.go, cmd/set.go, daemon/logic/engine.go
During import (or any situation where multiple credentials were being
submitted) the value of the first credential would be set for all
subsequent credentials.
=> Fix bug copying same value for each cred

cmd/credential_set.go, cmd/credential_set_test.go, cmd/view.go, daemon/logic/engine.go
The responsibility for pruning out unset credentials now lives entirely
inside the daemon.
Related manifoldco/torus-cli#302
=> Handle unset credentials inside Daemon

CHANGELOG.md, daemon/crypto/engine.go, daemon/logic/credential_graph_key_index.go, daemon/logic/credential_graph_key_index_test.go, daemon/logic/engine.go, glide.lock, glide.yaml, registry/keyring.go
To remove duplication of unsealing of private keys, we've split `Unbox`ing into two explicit composable stages.
In order to leverage these changes, we've begun indexing graphs by the valid keyring membership used to include the targeted user/machine into the underlying ring.
Related #302
=> Separate unseal and unbox

CHANGELOG.md, cmd/keypairs.go, daemon/logic/engine.go, daemon/logic/utils.go, daemon/logic/worklog.go, registry/claimtree.go, registry/claimtree_test.go, registry/keypairs.go, registry/keypairs_test.go
This pull request contains three commits that build ontop of each other to introduce two different performance increases.
1. To make it easier to fetch and find keypairs, I've introduced the Keypairs struct which handles finding active keypairs to use.
2. To make it easier to fetch and pass around all public keys in an org, I've added methods to a Claimtree for finding active public keys for specific types.
3. Using the modularity introduced in 1/2, we can now fetch keypairs and the claimtree in parallel.
These changes touch every single core component of the daemon (worklog, appending and fetching secrets, org invite approval). So we'll need to test Torus exhaustively before doing a release.
Closes manifoldco/torus-cli#302
=> Remove duplicate Claimtree calls while parallelizing fetching of keypairs and claimtree

daemon/logic/utils.go
While introducing the claimtree in #314, a bug was introduced preventing
an identities active encryption key from being found. This prevented
creation and encoding of users into keyrings.
=> Fix bug preventing credential graph creation

CHANGELOG.md, apitypes/credential_test.go, daemon/logic/engine.go
Old credentials that are stored under a v1 Credential data structure
were not being decrypted due to a string quotation bug.
To fix this bug, we now quote the string appropriately before
unmarshalling the credential value to check if it's unset inside the
daemon.
=> Fix bug preventing v1 creds from being decrypted

CHANGELOG.md, daemon/crypto/engine.go, daemon/crypto/secure/secure.go, daemon/crypto/secure/secure_test.go, daemon/daemon.go, daemon/logic/engine.go, daemon/logic/machine.go, daemon/logic/session.go, daemon/logic/utils.go, daemon/session/session.go, daemon/socket/proxy.go, glide.lock, glide.yaml, registry/client.go
Instead of storing long lived encryption keys in standard memory which
can be swapped to disk or core dumped sensitive data is stored inside
guarded memory using the excellent golang
[memguard](github.com/awnumar/memguard) library.
Some values may be stored in non-secure memory during signup or login.
=> Leverage memguard to securely store keys and tokens

CHANGELOG.md, cmd/export.go, cmd/import.go, cmd/set.go, cmd/view.go, cmd/view_test.go, docs/commands/secrets.md, hints/hints.go, internal/qa.md
The `export` command makes it easy to export secrets for a specific
environment and service to a file or into a shell environment (such as
fish, bash, powershell, etc).
Closes manifoldco/torus-cli#324
=> Introduce torus export command

api/credentials.go, apitypes/credential.go, apitypes/credential_test.go, cmd/ls.go, daemon/logic/engine.go, daemon/logic/utils.go, daemon/routes/credentials.go
When a user is listing credentials via `torus ls` we no longer decrypt
each credential. Instead we return a credential with no value and a type
of `undecrypted`.
This is a step to implementing `torus list`.
Related manifoldco/torus-cli#322
=> Skip decryption of credentials when listing

CHANGELOG.md, cmd/export.go, docs/commands/secrets.md
A user can now export secrets from torus to the `tfvars` file format.
Related #318
=>  Introduce `tfvars` format to torus export 

CHANGELOG.md, cmd/middleware.go, ui/ui.go
Status messages such as trying to log into an account are only printed
to stdout if a terminal is attached.
=> Only print to stdout if attached to terminal

cmd/orgs.go, cmd/policies.go, cmd/teams.go
In several places we were not filtering out nil errors when we needed to
return multiple errors at once.
We now use `errs.MultiError` to filter out nil errors :)
=> Filter out nil errors when returning multiple

cmd/projects.go
If an org had no projects, a panic would occur as we were assuming an
error must exist.
=> Fix panic when org has no projects

cmd/allow.go, cmd/invites_accept.go, cmd/policies.go, cmd/prompts.go, validate/validate.go
We now return more informative errors to the user when validating slugs
and names across the cli.
At the same time as doing this, I refactored to reduce repetition across
our usage of promptui.
Closes #342
=> Improve validation errors displayed to users

Dockerfile, Gopkg.lock, Gopkg.toml, Makefile, ui/ui.go
Often our build was breaking due to changes in one of our build
dependencies such as `gometalinter`.
To work around this, I've adopted a vendoring strategy for these
binaries which are built into `vendor/bin/$NAME`. Then everything that
requires this dependency in the Makefile runs the binary from that
location.
Closes manifoldco/torus-cli#286
=> Vendor build dependencies

CHANGELOG.md, cmd/allow.go, cmd/export.go, cmd/flags.go, cmd/import.go, cmd/invites.go, cmd/keypairs.go, cmd/list.go, cmd/orgs.go, cmd/policies.go, cmd/run.go, cmd/set.go, cmd/status.go, cmd/teams.go, cmd/unset.go, cmd/utils.go, cmd/utils_test.go, cmd/view.go, docs/commands/access-control.md, docs/commands/organizations.md, docs/commands/project-structure.md, docs/commands/secrets.md, docs/concepts/context.md, docs/concepts/path.md, docs/concepts/policies.md, docs/start-here/quickstart.md, internal/qa.md, prompts/select.go
After many discussions with users, we've decided to remove the concept
of instance and identity from the torus secret storage mechanism.
A very small amount of users have ever taken advantage of the
functionality whilst it's added a large level of complexity making it
vastly more difficult for a user to onboard and fully take advantage of
torus.
A user can still set/unset a secret for a specific instance/identity
pair by providing the full seven segment path. If a secret has been set
for this level of specificity the full 7 segment path will be displayed
via `torus view` or `torus list`. However, in all other cases, a 5
segment path will be displayed (e.g. `/org/project/env/sevice/secret`).
To support these changes the docs have been updated and expanded where
necessary.
=> Deprecate concept of instance and identity

CHANGELOG.md, cmd/run.go, docs/commands/secrets.md, pathexp/pathexp.go
Torus will now inject the current org, project, environment, and serivce
when a process is executed via `torus run`. These will be accessible via
`TORUS_ORG`, `TORUS_PROJECT`, `TORUS_ENVIRONMENT`, and `TORUS_SERVICE`.
Closes #258
=> Inject project structure via `torus run`

Gopkg.toml, appveyor.yml
With 0.4.0, dep now runs `prune` automatically when when using `ensure`.
Dep will check in the manifest for what options are needed for pruning.
This commit sets the prune settings to remove non-go files (exlcuding
LICENSE and AUTHORS), go test files. Unused (non-imported) packages need
to be included because of the tools/ package.
=> Add dep prune options to dep manifest

Makefile
A few components of the Makefile were using `git describe` to figure out
the current tag. However, when the container is built it's done outside
of a git repository leading to a ton of non-important error messages
popping up.
Instead, we only call git describe if we're actually in a `.git` folder.
=> No longer warn if not in .git folder

apitypes/apitypes.go, cmd/list.go, cmd/logout.go, daemon/logic/session.go, daemon/routes/routes.go, daemon/routes/types.go, registry/client.go, registry/round_tripper.go
In certain circumstances a StatusCode would not be set on an
apitypes.Error. Instead of having to set two properties, I've added a
lookup map for each error type, expanded the error types and added
functionality for converting an error type to a status code nad back.
This should prevent this specific bug from occurring in the future.
=> Fix bug preventing an error from being mutated

CHANGELOG.md, cmd/machines.go, cmd/orgs.go, cmd/services.go, cmd/teams.go, cmd/unset.go, cmd/utils.go
Org removal was missing a confirmation prompt while unset and machine
destroy were defaulting to "yes" instead of "no" when prompting the
user.
=> Add confirm prompt to org removal

Makefile, tools/gh-releaser/main.go
Starting with `v0.29.0` we began uplaoding the binaries to the GitHub
Release along with the Torus CDN at `get.torus.sh`.
To ensure these releases are always available, I've updated the
gh-releaser tool to support upload binaries from a folder which will
only be done for production releases.
=> Automatically upload binaries to GitHub Release

CHANGELOG.md, cmd/cmd.go, cmd/signup.go, cmd/view.go, ui/spinner.go, ui/ui.go
We had expoed spinners through a few different apis in the ui layer, as
a result some were obeying the `core.progress` preference while others
were not. I've fixed this by pushing the responsibility for checking
whether a spinner should/is displayed into the actual spinner itself.
At the sametime, I've fixed a bug where it was possible for a spinner to
never be removed due to a panic.
Closes #376 #377
=> Spinners obey core.progress pref and unblock view

CHANGELOG.md, cmd/prefs.go, prefs/prefs.go, prefs/rcpath.go, prefs/rcpath_windows.go
If a user attempted to set a preference on a non-darwin operating system
it would fail silently. This is because we were ignoring errors from
`user.Current()` which requires c-go to get the current user.
Since we're not building Torus with c-go (on purpose), we'd get an error
back when we called that method on linux or windows. I've worked around
this by writing a shim and no longer using `user.Current()`.
Closes #375
=> Fix prefs set when not on darwin
